---
section: deploy
title: Ponga en marcha herramientas de ONTAP para VMware vSphere
entries:
- title: Requisitos previos
  url: "/deploy/sizing-requirements.html"
- title: Descargue las herramientas de ONTAP
  url: "/deploy/download-ontap-tools.html"
- title: Preparar la puesta en marcha de herramientas de ONTAP
  url: "/deploy/prepare-deployment.html"
- title: Implemente una configuraci贸n de un solo nodo que no sea de alta disponibilidad
  url: "/deploy/nonha-deployment.html"
- title: Implemente una configuraci贸n de alta disponibilidad
  url: "/deploy/ha-three-node-deployment.html"
- title: Recupere sus herramientas de ONTAP para la configuraci贸n de VMware vSphere
  url: "/deploy/recovery-deployment.html"
- title: C贸digos de error de despliegue
  url: "/deploy/deployment-error-codes.html"
